Resources:
  MarketPlaceDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.MarketPlaceDB}
      AttributeDefinitions:
        - AttributeName: objectId
          AttributeType: S
        - AttributeName: objectName
          AttributeType: S
        - AttributeName: productType
          AttributeType: S
        - AttributeName: orderDate
          AttributeType: S

      KeySchema:
        - AttributeName: objectId
          KeyType: HASH
        - AttributeName: objectName
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI
          KeySchema:
            - AttributeName: productType
              KeyType: HASH
            - AttributeName: orderDate
              KeyType: RANGE
          Projection:
            ProjectionType: "KEYS_ONLY"
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}